CREATE DATABASE webapp_db;

CREATE TABLE reports (
  id SERIAL PRIMARY KEY,
  code VARCHAR(5000) NOT NULL,
  report VARCHAR(255) NOT NULL,
);

CREATE TABLE OWASP_description (
  id SERIAL PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  TEXT NOT NULL,
);

CREATE TABLE vulnerabilities (
  id SERIAL PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  TEXT NOT NULL,
);






