version: '3.9'

networks:
  bsc-group-17:
    external: true

services:
  bsc-group-17-code-val:
    container_name: bsc-group-17-code-val
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "30002:30002"
    networks:
      - bsc-group-17
