version: '3.9'

services:
  db:
    image: postgres
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
    #TODO: Change the following environment variables 
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_USER: USER
    networks:
      - webapp-network

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - webapp-network