version: "3.8"

networks:
  bsc-group-17:
    external: true

services:
  bsc-group-17-llm:
    container_name: bsc-group-17-llm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tokenizer:/usr/src/app/tokenizer
      - ./model:/usr/src/app/model
      - ./logs:/usr/src/logs
    #ports:
    #  - "30003:30003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['6', '7']
              capabilities: ['gpu']
    networks:
      - bsc-group-17
