version: '3.9'

networks:
  webapp-network:
    external: false

services:
  db:
    image: postgres
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp-network

  server:
    build:
      context: /server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    env_file:
      - /.env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    networks:
      - webapp-network

  webapp:
    build:
      context: /client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8500:8500
    networks:
      - webapp-network
    depends_on:
      - server

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - webapp-network