version: '3.9'

networks:
  webappdb:
    external: false

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webappdb
    ports:
      - "5432:5432"
    volumes:
      - appdata:/var/lib/postgresql/data
  backend:
    build : ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_NAME: webappdb
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  appdata:
