version: '3.9'

networks:
  bsc-group-17:
    external: true

services:
  bsc-group-17-web-db:
    container_name: bsc-group-17-web-db
    image: postgres:16.2
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bsc-group-17

  bsc-group-17-web-server:
    container_name: bsc-group-17-web-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3001:3001
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    networks:
      - bsc-group-17

  bsc-group-17-webapp:
    container_name: bsc-group-17-webapp
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8500:8500
    networks:
      - bsc-group-17
    depends_on:
      - server

  bsc-group-17-adminer:
    container_name: bsc-group-17-adminer
    image: adminer:4.8.1
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - bsc-group-17

volumes: 
  postgres-data:
