name: Code Validator Tests

on:
  push:
    branches:
      - code-validator
  pull_request:
    branches:
      - code-validator

jobs:
  test-code-validator:
    name: Run Code Validator Tests 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        pip install -r services/code-validator/src/requirements.txt
        pip install pytest httpx


    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
      
    - name: Run pytest
      run: pytest --junitxml=reports/results.xml services/code-validator/tests/test.py

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: code-validator-test-results
        path: reports/
