name: testing_extension
# This workflow is triggered on pushes to the extension branch
on: 
  push:
    branches:
      - extension

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: List contents of the extension directory
        run: ls services/extension
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./services/extension
      - name: Run tests
        run: npm test
        working-directory: ./services/extension
