name: Code Validator Tests and Build

on:
  push:
    paths:
      - 'services/code-validator/**'
  pull_request:
    paths:
      - 'services/code-validator/**'
  workflow_dispatch:


jobs:
  test-code-validator:
    name: Run Code Validator Tests 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        pip install -r services/code-validator/src/requirements.txt
        pip install pytest httpx

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
      
    - name: Run pytest
      run: pytest --junitxml=reports/results.xml services/code-validator/tests/test.py

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: code-validator-test-results
        path: reports/

  build-and-push-docker:
    name: Build and Push Docker Image to GitHub Packages
    needs: test-code-validator
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          REPOSITORY_LOWER=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t $REPOSITORY_LOWER/code-validator:latest services/code-validator/
          docker push $REPOSITORY_LOWER/code-validator:latest
          